// Sidebar navigation items per role. Icons are lucide-react names resolved in Sidebar.

export const NAV = {
  super_admin: [
    { label: "Dashboard", href: "/admin/dashboard", icon: "LayoutDashboard" },
    { label: "Schools / Branches", href: "/admin/schools", icon: "Building2" },
    { label: "Classes", href: "/admin/classes", icon: "School" },
    { label: "Subjects", href: "/admin/subjects", icon: "BookOpen" },
    { label: "Academic Years", href: "/admin/academic-years", icon: "CalendarRange" },
    { label: "Timetable", href: "/admin/timetable", icon: "Clock" },
    { label: "Students", href: "/admin/students", icon: "GraduationCap" },
    { label: "Promote Students", href: "/admin/students/promote", icon: "ArrowUpCircle" },
    { label: "Teachers", href: "/admin/teachers", icon: "Users" },
    { label: "Assign Teachers", href: "/admin/teachers/assign", icon: "UserPlus" },
    { label: "Parents", href: "/admin/parents", icon: "UserSquare2" },
    { label: "Staff", href: "/admin/staff", icon: "Briefcase" },
    { label: "Certificates", href: "/admin/certificates", icon: "Award" },
    { label: "Discipline", href: "/admin/discipline", icon: "ShieldAlert" },
    { label: "Employee Reviews", href: "/admin/reviews", icon: "Star" },
    { label: "Staff Attendance", href: "/hr/employee-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/admin/complaints", icon: "MessageSquareWarning" },
    { label: "Announcements", href: "/admin/announcements", icon: "Megaphone" },
    { label: "Notice Board", href: "/admin/notice-board", icon: "Pin" },
    { label: "Events", href: "/admin/events", icon: "CalendarDays" },
    { label: "Holidays", href: "/admin/holidays", icon: "Palmtree" },
    { label: "Documents", href: "/admin/documents", icon: "FileText" },
    { label: "Online Classes", href: "/admin/online-classes", icon: "Video" },
    { label: "PTM", href: "/admin/ptm", icon: "CalendarClock" },
    { label: "Visitors", href: "/admin/visitors", icon: "UserCheck" },
    { label: "Import Students", href: "/admin/import/students", icon: "Upload" },
    { label: "ID Cards", href: "/admin/id-cards", icon: "IdCard" },
    { label: "Email Templates", href: "/admin/email-templates", icon: "Mail" },
    { label: "Staff Passwords", href: "/admin/staff/passwords", icon: "KeyRound" },
    { label: "Fee Structure", href: "/admin/fee-structure", icon: "ReceiptText" },
    { label: "Shop Dashboard", href: "/admin/shop/dashboard", icon: "ShoppingBag" },
    { label: "Shop Products", href: "/admin/shop/products", icon: "Package" },
    { label: "Shop Orders", href: "/admin/shop/orders", icon: "ClipboardList" },
    { label: "Chat", href: "/chat", icon: "MessagesSquare" },
    { label: "Reports", href: "/admin/reports/attendance", icon: "BarChart3" },
    { label: "Audit Logs", href: "/admin/audit-logs", icon: "ScrollText" },
    { label: "Backup", href: "/admin/backup", icon: "DatabaseBackup" },
    { label: "Settings", href: "/admin/settings", icon: "Settings" },
  ],
  admin: null, // filled below = same as super_admin minus schools
  teacher: [
    { label: "Dashboard", href: "/teacher/dashboard", icon: "LayoutDashboard" },
    { label: "Timetable", href: "/teacher/timetable", icon: "Clock" },
    { label: "Attendance", href: "/teacher/attendance", icon: "ClipboardCheck" },
    { label: "QR Attendance", href: "/teacher/attendance/qr", icon: "QrCode" },
    { label: "Attendance Report", href: "/teacher/attendance/report", icon: "BarChart3" },
    { label: "Exams", href: "/teacher/exams", icon: "FileSpreadsheet" },
    { label: "Assignments", href: "/teacher/assignments", icon: "BookMarked" },
    { label: "Online Classes", href: "/teacher/online-classes", icon: "Video" },
    { label: "My Students", href: "/teacher/students", icon: "GraduationCap" },
    { label: "Discipline", href: "/teacher/discipline", icon: "ShieldAlert" },
    { label: "Leave", href: "/teacher/leave", icon: "CalendarOff" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "My Reviews", href: "/teacher/reviews", icon: "Star" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
    { label: "PTM", href: "/teacher/ptm", icon: "CalendarClock" },
    { label: "Chat", href: "/chat", icon: "MessagesSquare" },
    { label: "Messages", href: "/messages", icon: "Mail" },
    { label: "Announcements", href: "/announcements", icon: "Megaphone" },
  ],
  student: [
    { label: "Dashboard", href: "/student/dashboard", icon: "LayoutDashboard" },
    { label: "Timetable", href: "/student/timetable", icon: "Clock" },
    { label: "Attendance", href: "/student/attendance", icon: "ClipboardCheck" },
    { label: "Exams", href: "/student/exams", icon: "FileSpreadsheet" },
    { label: "Marks", href: "/student/marks", icon: "BarChart3" },
    { label: "Report Card", href: "/student/report-card", icon: "FileText" },
    { label: "Assignments", href: "/student/assignments", icon: "BookMarked" },
    { label: "Online Classes", href: "/student/online-classes", icon: "Video" },
    { label: "Fees", href: "/student/fees", icon: "CreditCard" },
    { label: "Library", href: "/student/library", icon: "Library" },
    { label: "Transport", href: "/student/transport", icon: "Bus" },
    { label: "Hostel", href: "/student/hostel", icon: "Building" },
    { label: "Health", href: "/student/health", icon: "HeartPulse" },
    { label: "Documents", href: "/student/documents", icon: "FileText" },
    { label: "My QR Code", href: "/student/qr-code", icon: "QrCode" },
    { label: "School Shop", href: "/student/shop", icon: "ShoppingBag" },
    { label: "My Shop Orders", href: "/student/shop/orders", icon: "Package" },
    { label: "Rate Teachers", href: "/student/reviews", icon: "Star" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
    { label: "Discipline", href: "/student/discipline", icon: "ShieldAlert" },
    { label: "Events", href: "/events", icon: "CalendarDays" },
    { label: "Messages", href: "/messages", icon: "Mail" },
    { label: "Announcements", href: "/announcements", icon: "Megaphone" },
  ],
  parent: [
    { label: "Dashboard", href: "/parent/dashboard", icon: "LayoutDashboard" },
    { label: "Children", href: "/parent/children", icon: "Users" },
    { label: "Attendance", href: "/parent/attendance", icon: "ClipboardCheck" },
    { label: "Marks", href: "/parent/marks", icon: "BarChart3" },
    { label: "Report Card", href: "/parent/report-card", icon: "FileText" },
    { label: "Fees", href: "/parent/fees", icon: "CreditCard" },
    { label: "School Shop", href: "/parent/shop", icon: "ShoppingBag" },
    { label: "My Shop Orders", href: "/parent/shop/orders", icon: "Package" },
    { label: "Timetable", href: "/parent/timetable", icon: "Clock" },
    { label: "Assignments", href: "/parent/assignments", icon: "BookMarked" },
    { label: "Discipline", href: "/parent/discipline", icon: "ShieldAlert" },
    { label: "Health", href: "/parent/health", icon: "HeartPulse" },
    { label: "Transport", href: "/parent/transport", icon: "Bus" },
    { label: "Hostel", href: "/parent/hostel", icon: "Building" },
    { label: "Events", href: "/events", icon: "CalendarDays" },
    { label: "PTM", href: "/parent/ptm", icon: "CalendarClock" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
    { label: "Messages", href: "/messages", icon: "Mail" },
    { label: "Announcements", href: "/announcements", icon: "Megaphone" },
  ],
  accountant: [
    { label: "Dashboard", href: "/accountant/dashboard", icon: "LayoutDashboard" },
    { label: "Fee Structure", href: "/accountant/fee-structure", icon: "ListChecks" },
    { label: "Invoices", href: "/accountant/invoices", icon: "ReceiptText" },
    { label: "Generate Invoices", href: "/accountant/invoices/generate", icon: "FilePlus2" },
    { label: "Overdue", href: "/accountant/invoices/overdue", icon: "AlertTriangle" },
    { label: "Payments", href: "/accountant/payments", icon: "CreditCard" },
    { label: "Expenses", href: "/accountant/expenses", icon: "Wallet" },
    { label: "Gateway Logs", href: "/accountant/gateway-logs", icon: "Network" },
    { label: "Reports", href: "/accountant/reports", icon: "BarChart3" },
    { label: "Shop · Verify Code", href: "/accountant/shop/verify", icon: "ScanLine" },
    { label: "Shop · Pending Pickups", href: "/accountant/shop/pending", icon: "Clock" },
    { label: "Shop · Orders", href: "/admin/shop/orders", icon: "ClipboardList" },
    { label: "Shop · Products", href: "/admin/shop/products", icon: "Package" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
  ],
  librarian: [
    { label: "Dashboard", href: "/library/dashboard", icon: "LayoutDashboard" },
    { label: "Books", href: "/library/books", icon: "BookOpen" },
    { label: "Issue Book", href: "/library/issue", icon: "BookUp" },
    { label: "Return Book", href: "/library/return", icon: "BookDown" },
    { label: "Members", href: "/library/members", icon: "Users" },
    { label: "Reports", href: "/library/reports", icon: "BarChart3" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
  ],
  transport_manager: [
    { label: "Dashboard", href: "/transport/dashboard", icon: "LayoutDashboard" },
    { label: "Vehicles", href: "/transport/vehicles", icon: "Bus" },
    { label: "Routes", href: "/transport/routes", icon: "Map" },
    { label: "Students", href: "/transport/students", icon: "GraduationCap" },
    { label: "Assign", href: "/transport/assign", icon: "UserPlus" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
  ],
  hostel_warden: [
    { label: "Dashboard", href: "/hostel/dashboard", icon: "LayoutDashboard" },
    { label: "Rooms", href: "/hostel/rooms", icon: "DoorOpen" },
    { label: "Allocate", href: "/hostel/allocate", icon: "UserPlus" },
    { label: "Students", href: "/hostel/students", icon: "GraduationCap" },
    { label: "Fees", href: "/hostel/fees", icon: "CreditCard" },
    { label: "Reports", href: "/hostel/reports", icon: "BarChart3" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
  ],
  hr_manager: [
    { label: "Dashboard", href: "/hr/dashboard", icon: "LayoutDashboard" },
    { label: "Staff", href: "/hr/staff", icon: "Users" },
    { label: "Staff Attendance", href: "/hr/employee-attendance", icon: "CalendarCheck" },
    { label: "Leave Types", href: "/hr/leave-types", icon: "ListChecks" },
    { label: "Leaves", href: "/hr/leaves", icon: "CalendarOff" },
    { label: "Leave Balances", href: "/hr/leave-balances", icon: "Scale" },
    { label: "Payroll", href: "/hr/payroll", icon: "Banknote" },
    { label: "Employee Reviews", href: "/admin/reviews", icon: "Star" },
    { label: "Complaints", href: "/admin/complaints", icon: "MessageSquareWarning" },
    { label: "Chat", href: "/chat", icon: "MessagesSquare" },
    { label: "Reports", href: "/hr/reports", icon: "BarChart3" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
  ],
  health_officer: [
    { label: "Dashboard", href: "/health/dashboard", icon: "LayoutDashboard" },
    { label: "Health Records", href: "/health/records", icon: "HeartPulse" },
    { label: "Medical Visits", href: "/health/visits", icon: "Stethoscope" },
    { label: "Reports", href: "/health/reports", icon: "BarChart3" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
  ],
  security_guard: [
    { label: "Dashboard", href: "/visitor/dashboard", icon: "LayoutDashboard" },
    { label: "Check In", href: "/visitor/checkin", icon: "LogIn" },
    { label: "Check Out", href: "/visitor/checkout", icon: "LogOut" },
    { label: "Visitor Log", href: "/visitor/log", icon: "ScrollText" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
  ],
  canteen_manager: [
    { label: "Dashboard", href: "/canteen/dashboard", icon: "LayoutDashboard" },
    { label: "Menu", href: "/canteen/menu", icon: "UtensilsCrossed" },
    { label: "Orders", href: "/canteen/orders", icon: "ShoppingCart" },
    { label: "Reports", href: "/canteen/reports", icon: "BarChart3" },
    { label: "My Salary", href: "/salary", icon: "Wallet" },
    { label: "My Attendance", href: "/my-attendance", icon: "CalendarCheck" },
    { label: "Complaints", href: "/complaints", icon: "MessageSquareWarning" },
  ],
};

// Admin = super_admin nav without the Schools/Branches item.
NAV.admin = NAV.super_admin.filter((i) => i.href !== "/admin/schools");

export function navForRole(role) {
  return NAV[role] || [];
}
